"""Non-executable multi-timeframe decision construction for AlphaMaster."""

from .ablation import default_ablation_variants, freeze_ablation_window
from .alpha_adapter import (
    evaluate_alpha_observation,
    evaluate_alpha_observations_at_indices,
    evaluate_alpha_observations_causal_prefix,
    load_alpha_strategy,
)
from .fusion import (
    ALPHA_H1,
    ALPHA_M15,
    DIRECTION_THRESHOLD,
    ENTRY_THRESHOLD,
    M5_ALPHA,
    PA_H1,
    PA_M15_CONTEXT,
    PA_M15_PATTERN,
    PA_M5_TIMING,
    classify_candidate_freshness,
    default_module_selection,
    fuse_signals,
    resolve_fusion_weights,
)
from .models import (
    AlignedDecisionFrameV1,
    AlignedTimeframeV1,
    AblationVariantV1,
    AblationWindowV1,
    AlphaObservationV1,
    CandidateFreshnessStateV1,
    ClosedBarV1,
    FusionInputsV1,
    FusionSignalV1,
    FusionWeightsV1,
    InstrumentConstraintsV1,
    LoadedAlphaStrategyV1,
    ModuleSelectionV1,
    OrderPlanCandidateV1,
    OrderPlanGenerationV1,
    PACandidateOccurrenceV1,
    PAObservationV1,
    TimeframeSeriesV1,
)
from .order_candidates import generate_order_plans
from .pa_adapter import build_pa_observation, evaluate_pa_observations_at_indices
from .time_alignment import (
    MAX_EXPECTED_CLOSURE_SECONDS,
    TIMEFRAME_SECONDS,
    align_decision_frame,
    assign_pa_continuity,
    bar_close_timestamp,
)

__all__ = [
    "AlignedDecisionFrameV1",
    "AlignedTimeframeV1",
    "AblationVariantV1",
    "AblationWindowV1",
    "AlphaObservationV1",
    "ALPHA_H1",
    "ALPHA_M15",
    "CandidateFreshnessStateV1",
    "ClosedBarV1",
    "DIRECTION_THRESHOLD",
    "ENTRY_THRESHOLD",
    "FusionInputsV1",
    "FusionSignalV1",
    "FusionWeightsV1",
    "InstrumentConstraintsV1",
    "LoadedAlphaStrategyV1",
    "M5_ALPHA",
    "MAX_EXPECTED_CLOSURE_SECONDS",
    "ModuleSelectionV1",
    "OrderPlanCandidateV1",
    "OrderPlanGenerationV1",
    "PACandidateOccurrenceV1",
    "PAObservationV1",
    "PA_H1",
    "PA_M15_CONTEXT",
    "PA_M15_PATTERN",
    "PA_M5_TIMING",
    "TIMEFRAME_SECONDS",
    "TimeframeSeriesV1",
    "align_decision_frame",
    "assign_pa_continuity",
    "bar_close_timestamp",
    "build_pa_observation",
    "classify_candidate_freshness",
    "default_module_selection",
    "default_ablation_variants",
    "evaluate_alpha_observation",
    "evaluate_alpha_observations_at_indices",
    "evaluate_alpha_observations_causal_prefix",
    "evaluate_pa_observations_at_indices",
    "fuse_signals",
    "freeze_ablation_window",
    "generate_order_plans",
    "load_alpha_strategy",
    "resolve_fusion_weights",
]
